apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: barneywang/chatbot:1.0.0-10
          ports:
            - containerPort: 3000
